CXX = g++
CXXFLAGS = -O3
LDLAGS = -O3
OBJS = main_file.o file1.o file2.o

all: hellomake

hellomake: $(OBJS)
	$(CXX) $(OBJS) -o hellomake $(LDLAGS)

main_file.o: main_file.cpp file1.h file2.h
	$(CXX) -c main_file.cpp $(CXXFLAGS)

file1.o: file1.cpp  file1.h 
	$(CXX) -c file1.cpp $(CXXFLAGS)

file2.o: file2.cpp  file2.h 
	$(CXX) -c file2.cpp $(CXXFLAGS)

.PHONY : clean
clean:
	rm -rf *.o hellomake
