all: hellomake

hellomake: main_file.o file1.o file2.o
	g++ main_file.o file1.o file2.o -o hellomake

main_file.o: main_file.cpp
	g++ -c main_file.cpp

file1.o: file1.cpp
	g++ -c file1.cpp

file2.o: file2.cpp
	g++ -c file2.cpp
