CXX = g++
CXXFLAGS = -O3
LDLAGS = -O3
PRG_NAME =  hellomake
HEADERS = file1.h file2.h
SOURCES = main_file.cpp file1.cpp file2.cpp
OBJS = $(SOURCES:.cpp=.o)

all: $(PRG_NAME)

# Включити всі наявні залежності
-include $(OBJS:.o=.d)

$(PRG_NAME): $(OBJS)
	$(CXX)  $(LDLAGS) $^ -o $@ 

%.o: %.cpp
	$(CXX) -c $(CXXFLAGS) $< 
	$(CXX) -MM -MP -MT $@  -MF $*.d $(CXXFLAGS) $<  
# Рядок вище генерує інформацію про залежності

.PHONY : clean
clean:
	rm -rf *.o *.d $(PRG_NAME)
