all: hellomake

hellomake: main_file.o file1.o file2.o
	g++ main_file.o file1.o file2.o -o hellomake

main_file.o: main_file.cpp file1.h file2.h
	g++ -c main_file.cpp

file1.o: file1.cpp  file1.h 
	g++ -c file1.cpp

file2.o: file2.cpp  file2.h 
	g++ -c file2.cpp
