CXX = g++
CXXFLAGS = -O3
LDLAGS = -O3
OBJS = main_file.o file1.o file2.o
PRG_NAME =  hellomake
HEADERS = file1.h file2.h

all: $(PRG_NAME)

$(PRG_NAME): $(OBJS)
	$(CXX) $^ -o $@ 

%.o: %.c $(HEADERS)
	$(CXX) -c $(CXXFLAGS) $< 

.PHONY : clean
clean:
	rm -rf *.o $(PRG_NAME)
