CXX = g++
CXXFLAGS = -O3
LDLAGS = -O3
OBJS = main_file.o file1.o file2.o
PRG_NAME =  hellomake

all: $(PRG_NAME)

$(PRG_NAME): $(OBJS)
	$(CXX) $^ -o $@ 

main_file.o: main_file.cpp file1.h file2.h
	$(CXX)  -c $(CXXFLAGS) $< 

file1.o: file1.cpp  file1.h 
	$(CXX)  -c $(CXXFLAGS) $< 

file2.o: file2.cpp  file2.h 
	$(CXX)  -c $(CXXFLAGS) $< 

.PHONY : clean
clean:
	rm -rf *.o $(PRG_NAME)
