CXX = g++
CXXFLAGS = -O3
LDLAGS = -O3
PRG_NAME =  hellomake
SOURCES = $(wildcard *.cpp)
OBJS = $(subst .cpp,.o,$(SOURCES))

all: $(PRG_NAME)

$(PRG_NAME): $(OBJS)

main_file.o: main_file.cpp file1.h file2.h
file1.o: file1.cpp file1.h 
file2.o: file2.cpp file2.h

.PHONY : clean
clean:
	rm -rf *.o $(PRG_NAME)
